language: ruby
dist: trusty
before_script:
  # clone frontend repo etc
script:
  - . repo_commits.sh
  - ./github_status.sh pending
  - ./test_runner.sh
after_success:
  - ./github_status.sh success
after_failure:
  - ./github_status.sh failure
